In [1]:
import cdsapi
import os
import time
import numpy as np
import pandas as pd

# this script is resumable for large downloads
# but you need to setup your cdsapi key first
# nano $HOME/.cdsapirc or nano ~/.cdsapirc

In [2]:
from download.cams_download import (
    read_cams_radiation_csv, process_and_save_csvs, 
    check_hourly_time_range_consistency,read_cams_hourly_csv,
    merge_cams_folder,engineer_features,build_grid_mapping,csv_to_npz_grid)

# ADS account:
url: https://ads.atmosphere.copernicus.eu/api
key: 4045ee2c-02ad-45a0-a02a-57c79c038421

# ADS 2 account:
url: https://ads.atmosphere.copernicus.eu/api
key: 66646d71-95a1-482a-900e-09d67eb18385

## ADS 3 account 
url: https://ads.atmosphere.copernicus.eu/api
key: 807b30a4-26d8-4e40-afc0-904bd9d6a0aa

## ADS 4 account
url: https://ads.atmosphere.copernicus.eu/api
key: 74164cde-7818-4e96-88b5-1137eccb859c

## ADS 5 account
url: https://ads.atmosphere.copernicus.eu/api
key: 930a7e62-ba60-400d-97aa-09a24a5e5f1a

In [3]:
# provider target grid points
vec = pd.read_csv("Data/grid/sub2_lon_lat_vectors.csv")

lon_sub2 = vec["longitude_50"].values
lat_sub2 = vec["latitude_50"].values

In [ ]:
# ---------------- 1. Generate grid over Hong Kong ----------------
lats = lat_sub2
lons = lon_sub2
points = [(round(lon, 4), round(lat, 4)) for lat in lats for lon in lons]

# ---------------- 2.  Constant request parts -------------------------
dataset   = "cams-solar-radiation-timeseries"
altitude  = ["0"]                                  # list!
date_span = ["2025-01-01/2025-01-02"]                  # list! ["2020-01-01/2025-06-19"]     
time_step = "15minute"
time_ref  = "universal_time"
sky_type  = "observed_cloud"                           # ALL-sky
fmt       = "csv"                               # underscore! csv_expert

# ---------------- 3.  ADS client and output folder -------------------
client  = cdsapi.Client()                              # uses ~/.cdsapirc
outdir  = "Data/CAMS/raw/2025/"  # output folder
os.makedirs(outdir, exist_ok=True)

# ---------------- 4.  Loop over every grid point ---------------------
for lon, lat in points:
    target = f"{outdir}/{lon}_{lat}.csv"
    if os.path.exists(target):
        continue                                       # skip if done
    req = {
        "sky_type"      : sky_type,
        "location"      : {"longitude": lon, "latitude": lat},
        "altitude"      : altitude,
        "date"          : date_span,
        "time_step"     : time_step,
        "time_reference": time_ref,
        "format"        : fmt
    }
    try:
        print(f"→ {lon},{lat}")
        client.retrieve(dataset, req).download(target)
        # time.sleep(1)                                
    except Exception as e:
        print(f"✖ {lon},{lat}  {e}")
# 2500 points

→ 113.64,22.86

2026-01-08 10:47:40,705 INFO Request ID is bf4b49a1-1359-44dc-a12d-7a79de8d2830
2026-01-08 10:47:41,134 INFO status has been updated to accepted
2026-01-08 10:47:51,000 INFO status has been updated to running
2026-01-08 10:48:04,517 INFO status has been updated to successful

→ 113.66,22.86

2026-01-08 10:48:12,775 INFO Request ID is c2359aaf-315e-44a5-bd95-98bbafdd9378
2026-01-08 10:48:13,199 INFO status has been updated to accepted
2026-01-08 10:48:28,530 INFO status has been updated to running
2026-01-08 10:48:48,384 INFO status has been updated to successful

→ 113.68,22.86

2026-01-08 10:48:56,514 INFO Request ID is fd1cc7f9-c67e-4752-92ca-eeaa8e747e62
2026-01-08 10:48:56,940 INFO status has been updated to accepted
2026-01-08 10:49:12,312 INFO status has been updated to running
2026-01-08 10:49:32,159 INFO status has been updated to successful

→ 113.7,22.86

2026-01-08 10:49:38,883 INFO Request ID is fd1ccb70-c26d-4cea-b0d7-8eac6b4ced43
2026-01-08 10:49:39,311 INFO status has been updated to accepted
2026-01-08 10:49:49,157 INFO status has been updated to running
2026-01-08 10:50:02,782 INFO status has been updated to successful

→ 113.72,22.86

2026-01-08 10:50:09,452 INFO Request ID is 868c118f-8863-4ae6-bbec-a2f4a6bf00a5
2026-01-08 10:50:09,866 INFO status has been updated to accepted
2026-01-08 10:50:33,238 INFO status has been updated to running
2026-01-08 10:50:45,048 INFO status has been updated to successful

→ 113.74,22.86

2026-01-08 10:50:51,652 INFO Request ID is bc8d89b7-4cbb-4b2a-a9d6-e2b4a4f3f11a
2026-01-08 10:50:52,244 INFO status has been updated to accepted
2026-01-08 10:51:07,590 INFO status has been updated to running
2026-01-08 10:51:15,601 INFO status has been updated to successful

→ 113.76,22.86

2026-01-08 10:51:22,192 INFO Request ID is 22b83cc2-96d0-4b43-8d09-cab75d7bde96
2026-01-08 10:51:22,610 INFO status has been updated to accepted
2026-01-08 10:51:37,907 INFO status has been updated to running
2026-01-08 10:52:15,257 INFO status has been updated to successful

→ 113.78,22.86

2026-01-08 10:52:21,941 INFO Request ID is 924aaa24-e8f4-47a4-824f-0faf14a478ad
2026-01-08 10:52:22,371 INFO status has been updated to accepted
2026-01-08 10:52:32,185 INFO status has been updated to running
2026-01-08 10:52:45,704 INFO status has been updated to successful

→ 113.8,22.86

2026-01-08 10:52:52,360 INFO Request ID is 22497f42-2a0f-4190-be97-6b59c72dea92
2026-01-08 10:52:52,788 INFO status has been updated to accepted
2026-01-08 10:53:08,110 INFO status has been updated to running
2026-01-08 10:53:28,202 INFO status has been updated to successful

→ 113.82,22.86

2026-01-08 10:53:36,083 INFO Request ID is 11d20c4f-3caa-440d-8b8f-ea1e72e5634b
2026-01-08 10:53:36,509 INFO status has been updated to accepted
2026-01-08 10:53:59,817 INFO status has been updated to running

In [ ]:
process_and_save_csvs(
    source_root='Data/CAMS/raw/2025',
    target_root='Data/CAMS/raw/2025_15mins',
    header_row=42, # no. depends on the actual file header
    mode='instant',
)

In [ ]:
valid, mismatches = check_hourly_time_range_consistency('Data/CAMS/2021-2024_15mins')

print(f"✅ {len(valid)} files have consistent time ranges.")

if mismatches:
    print(f"❌ {len(mismatches)} inconsistent files found:")
    for path, start, end, reason in mismatches:
        print(f" - {path}: {start} → {end} | {reason}")

In [6]:
merged = merge_cams_folder("Data/CAMS/2021-2024_15mins", "merged_2021-2024.csv")
print(merged.head())

           Observation period  TOA  Clear sky GHI  Clear sky BHI  \
0         2021-01-01 10:30:00  0.0            0.0            0.0
202188588 2021-01-01 10:30:00  0.0            0.0            0.0
157460322 2021-01-01 10:30:00  0.0            0.0            0.0
302722026 2021-01-01 10:30:00  0.0            0.0            0.0
313798932 2021-01-01 10:30:00  0.0            0.0            0.0

           Clear sky DHI  Clear sky BNI  GHI  BHI  DHI  BNI  Reliability  \
0                    0.0            0.0  0.0  0.0  0.0  0.0          1.0
202188588            0.0            0.0  0.0  0.0  0.0  0.0          1.0
157460322            0.0            0.0  0.0  0.0  0.0  0.0          1.0
302722026            0.0            0.0  0.0  0.0  0.0  0.0          1.0
313798932            0.0            0.0  0.0  0.0  0.0  0.0          1.0

           latitude  longitude  altitude
0             22.62     114.06       0.0
202188588     22.76     113.92       0.0
157460322     22.08     113.92       0.0
302722026     22.32     113.76       0.0
313798932     22.26     113.98       0.0

In [13]:
df, final_features = engineer_features(merged)

In [14]:
df, grid_shape = build_grid_mapping(merged)
df_f = df[final_features + ['row', 'col']].copy()

In [17]:
df_f.head()

,GHI,Clear sky GHI,Observation period,longitude,latitude,row,col
0,0.0,0.0,2021-01-01 10:30:00,114.06,22.62,12,21
202188588,0.0,0.0,2021-01-01 10:30:00,113.92,22.76,5,14
157460322,0.0,0.0,2021-01-01 10:30:00,113.92,22.08,39,14
302722026,0.0,0.0,2021-01-01 10:30:00,113.76,22.32,27,6
313798932,0.0,0.0,2021-01-01 10:30:00,113.98,22.26,30,17

In [ ]:
merged = merged['Observation period','Clear sky GHI','GHI',]

,Observation period,TOA,Clear sky GHI,Clear sky BHI,Clear sky DHI,Clear sky BNI,GHI,BHI,DHI,BNI,Reliability,latitude,longitude,altitude
0,2021-01-01 10:30:00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0,22.62,113.96,0.0
420642,2021-01-01 10:30:00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0,21.96,113.74,0.0
2875658,2021-01-01 10:30:00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0,22.58,113.70,0.0
560856,2021-01-01 10:30:00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0,22.86,114.34,0.0
701070,2021-01-01 10:30:00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0,22.06,114.22,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1402139,2024-12-31 23:45:00,60.4035,25.4167,7.9180,17.4987,45.6896,4.8037,0.0212,4.7825,0.1374,1.0,21.94,114.58,0.0
701069,2024-12-31 23:45:00,56.4632,23.6805,7.2856,16.3949,44.9102,6.8525,0.0362,6.8163,0.2185,1.0,22.86,114.34,0.0
841283,2024-12-31 23:45:00,58.2889,24.0797,7.3727,16.7069,44.0457,6.9399,0.0000,6.9399,0.0002,1.0,22.06,114.22,0.0
140213,2024-12-31 23:45:00,55.3414,22.4736,6.3936,16.0800,40.1779,9.3157,0.8473,8.4684,6.0481,1.0,22.62,113.96,0.0
3015871,2024-12-31 23:45:00,54.1952,21.3758,5.8331,15.5428,37.4036,10.5179,0.9862,9.5317,5.7583,1.0,22.58,113.70,0.0

In [19]:
data, time_arr = csv_to_npz_grid(
    df=df_f,
    out_path="ghi_grid2500_2ch_15mins.npz",
    grid_shape=(50, 50)
)

KeyboardInterrupt: